apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-currency-deploy
  labels:
    name: exchange-currency-deploy
    app: exchange-currency-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: exchange-currency-pod
      app: exchange-currency-app
  template:
    metadata:
      name: exchange-currency-pod
      labels:
        name: exchange-currency-pod
        app: exchange-currency-app
    spec:
      containers:
        - name: exchange-currency
          image: 752362912519.dkr.ecr.us-east-1.amazonaws.com/currency-exchange:v1
          command: ['sh', '-c', 'echo Currency Container is Running ; sleep 3600']
          ports:
            - containerPort: 8000
              hostPort: 0
