apiVersion: v1
kind: Service
metadata:
  name: exchange-currency-service
  labels:
    name: exchange-currency-service
    app: exchange-currency-app
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30006
  selector:
    name: exchange-currency-pod
    app: exchange-currency-app
